// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJnYBVcqWWj7itr8hvlp4kraUgJdhMWxE',
    appId: '1:943128152863:web:aa20aa0221e60e1f223e2a',
    messagingSenderId: '943128152863',
    projectId: 'app-listas-eccd1',
    authDomain: 'app-listas-eccd1.firebaseapp.com',
    storageBucket: 'app-listas-eccd1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhYUkswvJIoucewmh3gaIkIa8hy2bt_fc',
    appId: '1:943128152863:android:d0f2f0433b1e6031223e2a',
    messagingSenderId: '943128152863',
    projectId: 'app-listas-eccd1',
    storageBucket: 'app-listas-eccd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2xLICdk0Al6B4CiKGxnhX5kk2jLkumx0',
    appId: '1:943128152863:ios:152bf6233183284f223e2a',
    messagingSenderId: '943128152863',
    projectId: 'app-listas-eccd1',
    storageBucket: 'app-listas-eccd1.appspot.com',
    iosBundleId: 'com.example.appListas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2xLICdk0Al6B4CiKGxnhX5kk2jLkumx0',
    appId: '1:943128152863:ios:61d784db1b3d1934223e2a',
    messagingSenderId: '943128152863',
    projectId: 'app-listas-eccd1',
    storageBucket: 'app-listas-eccd1.appspot.com',
    iosBundleId: 'com.example.appListas.RunnerTests',
  );
}
